local colmakdhEmulation = true
local qwertyNormalModeEmulation = false

local setKeyMap = function()
    if colmakdhEmulation and qwertyNormalModeEmulation then
        print('invalid keyboard emulation settings')
        return
    end


    if colmakdhEmulation then
        vim.g.colmakdhEmulation = true
        vim.keymap.set({ 'i', 'c' }, 'e', 'f')
        vim.keymap.set({ 'i', 'c' }, 'E', 'F')
        vim.keymap.set({ 'i', 'c' }, 'j', 'n')
        vim.keymap.set({ 'i', 'c' }, 'J', 'N')
        vim.keymap.set({ 'i', 'c' }, 'r', 'b')
        vim.keymap.set({ 'i', 'c' }, 'R', 'P')
        vim.keymap.set({ 'i', 'c' }, 'r', 'p')
        vim.keymap.set({ 'i', 'c' }, 'f', 't')
        vim.keymap.set({ 'i', 'c' }, 'F', 'T')
        vim.keymap.set({ 'i', 'c' }, 'd', 's')
        vim.keymap.set({ 'i', 'c' }, 'D', 'S')
        vim.keymap.set({ 'i', 'c' }, 's', 'r')
        vim.keymap.set({ 'i', 'c' }, 'S', 'R')
        vim.keymap.set({ 'i', 'c' }, 'b', 'v')
        vim.keymap.set({ 'i', 'c' }, 'B', 'V')
        vim.keymap.set({ 'i', 'c' }, 't', 'b')
        vim.keymap.set({ 'i', 'c' }, 'T', 'B')
        vim.keymap.set({ 'i', 'c' }, 'v', 'd')
        vim.keymap.set({ 'i', 'c' }, 'V', 'D')
        vim.keymap.set({ 'i', 'c' }, 'l', 'i')
        vim.keymap.set({ 'i', 'c' }, 'L', 'I')
        vim.keymap.set({ 'i', 'c' }, 'o', 'y')
        vim.keymap.set({ 'i', 'c' }, 'O', 'Y')
        vim.keymap.set({ 'i', 'c' }, 'i', 'u')
        vim.keymap.set({ 'i', 'c' }, 'I', 'U')
        vim.keymap.set({ 'i', 'c' }, 'k', 'e')
        vim.keymap.set({ 'i', 'c' }, 'K', 'E')
        vim.keymap.set({ 'i', 'c' }, 'm', 'h')
        vim.keymap.set({ 'i', 'c' }, 'M', 'H')
        vim.keymap.set({ 'i', 'c' }, 'u', 'l')
        vim.keymap.set({ 'i', 'c' }, 'U', 'L')
        vim.keymap.set({ 'i', 'c' }, 'n', 'k')
        vim.keymap.set({ 'i', 'c' }, 'N', 'K')
        vim.keymap.set({ 'i', 'c' }, 'h', 'm')
        vim.keymap.set({ 'i', 'c' }, 'H', 'M')
        vim.keymap.set({ 'i', 'c' }, 'y', 'j')
        vim.keymap.set({ 'i', 'c' }, 'Y', 'J')
        vim.keymap.set({ 'i', 'c' }, 'p', ';')
        vim.keymap.set({ 'i', 'c' }, 'P', ':')
        vim.keymap.set({ 'i', 'c' }, ';', 'o')
        vim.keymap.set({ 'i', 'c' }, ':', 'O')
	else
        vim.g.colmakdhEmulation = false
		vim.keymap.set({ 'i', 'c' }, 'e', 'e')
		vim.keymap.set({ 'i', 'c' }, 'E', 'E')
		vim.keymap.set({ 'i', 'c' }, 'r', 'r')
		vim.keymap.set({ 'i', 'c' }, 'R', 'R')
		vim.keymap.set({ 'i', 'c' }, 'j', 'j')
		vim.keymap.set({ 'i', 'c' }, 'J', 'J')
        vim.keymap.set({ 'i', 'c' }, 'f', 'f')
        vim.keymap.set({ 'i', 'c' }, 'F', 'F')
        vim.keymap.set({ 'i', 'c' }, 'd', 'd')
        vim.keymap.set({ 'i', 'c' }, 'D', 'D')
        vim.keymap.set({ 'i', 'c' }, 's', 's')
        vim.keymap.set({ 'i', 'c' }, 'S', 'S')
        vim.keymap.set({ 'i', 'c' }, 'b', 'b')
        vim.keymap.set({ 'i', 'c' }, 'B', 'B')
        vim.keymap.set({ 'i', 'c' }, 't', 't')
        vim.keymap.set({ 'i', 'c' }, 'T', 'T')
        vim.keymap.set({ 'i', 'c' }, 'v', 'v')
        vim.keymap.set({ 'i', 'c' }, 'V', 'V')
        vim.keymap.set({ 'i', 'c' }, 'l', 'l')
        vim.keymap.set({ 'i', 'c' }, 'L', 'L')
        vim.keymap.set({ 'i', 'c' }, 'o', 'o')
        vim.keymap.set({ 'i', 'c' }, 'O', 'O')
        vim.keymap.set({ 'i', 'c' }, 'i', 'i')
        vim.keymap.set({ 'i', 'c' }, 'I', 'I')
        vim.keymap.set({ 'i', 'c' }, 'k', 'k')
        vim.keymap.set({ 'i', 'c' }, 'K', 'K')
        vim.keymap.set({ 'i', 'c' }, 'm', 'm')
        vim.keymap.set({ 'i', 'c' }, 'M', 'M')
        vim.keymap.set({ 'i', 'c' }, 'u', 'u')
        vim.keymap.set({ 'i', 'c' }, 'U', 'U')
        vim.keymap.set({ 'i', 'c' }, 'n', 'n')
        vim.keymap.set({ 'i', 'c' }, 'N', 'N')
        vim.keymap.set({ 'i', 'c' }, 'h', 'h')
        vim.keymap.set({ 'i', 'c' }, 'H', 'H')
        vim.keymap.set({ 'i', 'c' }, 'y', 'y')
        vim.keymap.set({ 'i', 'c' }, 'Y', 'Y')
        vim.keymap.set({ 'i', 'c' }, 'p', 'p')
        vim.keymap.set({ 'i', 'c' }, 'P', 'P')
        vim.keymap.set({ 'i', 'c' }, ';', ';')
        vim.keymap.set({ 'i', 'c' }, ':', ':')
	end

    if qwertyNormalModeEmulation then
        print('nqwerty')
        vim.keymap.set({ 'n', 'v' }, 'f', 'e')
        vim.keymap.set({ 'n', 'v' }, 'F', 'E')
        vim.keymap.set({ 'n', 'v' }, 'n', 'j')
        vim.keymap.set({ 'n', 'v' }, 'N', 'J')
        vim.keymap.set({ 'n', 'v' }, 'b', 'r')
        vim.keymap.set({ 'n', 'v' }, 'P', 'R')
        vim.keymap.set({ 'n', 'v' }, 'p', 'r')
        vim.keymap.set({ 'n', 'v' }, 't', 'f')
        vim.keymap.set({ 'n', 'v' }, 'T', 'F')
        vim.keymap.set({ 'n', 'v' }, 's', 'd')
        vim.keymap.set({ 'n', 'v' }, 'S', 'D')
        vim.keymap.set({ 'n', 'v' }, 'r', 's')
        vim.keymap.set({ 'n', 'v' }, 'R', 'S')
        vim.keymap.set({ 'n', 'v' }, 'v', 'b')
        vim.keymap.set({ 'n', 'v' }, 'V', 'B')
        vim.keymap.set({ 'n', 'v' }, 'b', 't')
        vim.keymap.set({ 'n', 'v' }, 'B', 'T')
        vim.keymap.set({ 'n', 'v' }, 'd', 'v')
        vim.keymap.set({ 'n', 'v' }, 'D', 'V')
        vim.keymap.set({ 'n', 'v' }, 'i', 'l')
        vim.keymap.set({ 'n', 'v' }, 'I', 'L')
        vim.keymap.set({ 'n', 'v' }, 'y', 'o')
        vim.keymap.set({ 'n', 'v' }, 'Y', 'O')
        vim.keymap.set({ 'n', 'v' }, 'u', 'i')
        vim.keymap.set({ 'n', 'v' }, 'U', 'I')
        vim.keymap.set({ 'n', 'v' }, 'e', 'k')
        vim.keymap.set({ 'n', 'v' }, 'E', 'K')
        vim.keymap.set({ 'n', 'v' }, 'h', 'm')
        vim.keymap.set({ 'n', 'v' }, 'H', 'M')
        vim.keymap.set({ 'n', 'v' }, 'l', 'u')
        vim.keymap.set({ 'n', 'v' }, 'L', 'U')
        vim.keymap.set({ 'n', 'v' }, 'k', 'n')
        vim.keymap.set({ 'n', 'v' }, 'K', 'N')
        vim.keymap.set({ 'n', 'v' }, 'm', 'h')
        vim.keymap.set({ 'n', 'v' }, 'M', 'H')
        vim.keymap.set({ 'n', 'v' }, 'j', 'y')
        vim.keymap.set({ 'n', 'v' }, 'J', 'Y')
        vim.keymap.set({ 'n', 'v' }, ';', 'p')
        vim.keymap.set({ 'n', 'v' }, ':', 'P')
        vim.keymap.set({ 'n', 'v' }, 'o', ';')
        vim.keymap.set({ 'n', 'v' }, 'O', ':')

        vim.keymap.set({ 'n', 'v', 'i' }, '<C-f>', '<C-e>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-F>', '<C-E>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-n>', '<C-j>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-N>', '<C-J>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-b>', '<C-r>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-P>', '<C-R>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-p>', '<C-r>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-t>', '<C-f>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-T>', '<C-F>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-s>', '<C-d>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-S>', '<C-D>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-r>', '<C-s>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-R>', '<C-S>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-v>', '<C-b>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-V>', '<C-B>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-b>', '<C-t>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-B>', '<C-T>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-d>', '<C-v>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-D>', '<C-V>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-i>', '<C-l>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-I>', '<C-L>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-y>', '<C-o>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-Y>', '<C-O>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-u>', '<C-i>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-U>', '<C-I>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-e>', '<C-k>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-E>', '<C-K>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-h>', '<C-m>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-H>', '<C-M>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-l>', '<C-u>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-L>', '<C-U>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-k>', '<C-n>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-K>', '<C-N>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-m>', '<C-h>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-M>', '<C-H>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-j>', '<C-y>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-J>', '<C-Y>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-;>', '<C-p>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-:>', '<C-P>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-o>', '<C-;>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-O>', '<C-:>')
	else
		vim.keymap.set({ 'n', 'v' }, 'e', 'e')
		vim.keymap.set({ 'n', 'v' }, 'E', 'E')
		vim.keymap.set({ 'n', 'v' }, 'r', 'r')
		vim.keymap.set({ 'n', 'v' }, 'R', 'R')
		vim.keymap.set({ 'n', 'v' }, 'j', 'j')
		vim.keymap.set({ 'n', 'v' }, 'J', 'J')
        vim.keymap.set({ 'n', 'v' }, 'f', 'f')
        vim.keymap.set({ 'n', 'v' }, 'F', 'F')
        vim.keymap.set({ 'n', 'v' }, 'd', 'd')
        vim.keymap.set({ 'n', 'v' }, 'D', 'D')
        vim.keymap.set({ 'n', 'v' }, 's', 's')
        vim.keymap.set({ 'n', 'v' }, 'S', 'S')
        vim.keymap.set({ 'n', 'v' }, 'b', 'b')
        vim.keymap.set({ 'n', 'v' }, 'B', 'B')
        vim.keymap.set({ 'n', 'v' }, 't', 't')
        vim.keymap.set({ 'n', 'v' }, 'T', 'T')
        vim.keymap.set({ 'n', 'v' }, 'v', 'v')
        vim.keymap.set({ 'n', 'v' }, 'V', 'V')
        vim.keymap.set({ 'n', 'v' }, 'l', 'l')
        vim.keymap.set({ 'n', 'v' }, 'L', 'L')
        vim.keymap.set({ 'n', 'v' }, 'o', 'o')
        vim.keymap.set({ 'n', 'v' }, 'O', 'O')
        vim.keymap.set({ 'n', 'v' }, 'i', 'i')
        vim.keymap.set({ 'n', 'v' }, 'I', 'I')
        vim.keymap.set({ 'n', 'v' }, 'k', 'k')
        vim.keymap.set({ 'n', 'v' }, 'K', 'K')
        vim.keymap.set({ 'n', 'v' }, 'm', 'm')
        vim.keymap.set({ 'n', 'v' }, 'M', 'M')
        vim.keymap.set({ 'n', 'v' }, 'u', 'u')
        vim.keymap.set({ 'n', 'v' }, 'U', 'U')
        vim.keymap.set({ 'n', 'v' }, 'n', 'n')
        vim.keymap.set({ 'n', 'v' }, 'N', 'N')
        vim.keymap.set({ 'n', 'v' }, 'h', 'h')
        vim.keymap.set({ 'n', 'v' }, 'H', 'H')
        vim.keymap.set({ 'n', 'v' }, 'y', 'y')
        vim.keymap.set({ 'n', 'v' }, 'Y', 'Y')
        vim.keymap.set({ 'n', 'v' }, 'p', 'p')
        vim.keymap.set({ 'n', 'v' }, 'P', 'P')
        vim.keymap.set({ 'n', 'v' }, ';', ';')
        vim.keymap.set({ 'n', 'v' }, ':', ':')

        vim.keymap.set({ 'n', 'v', 'i' }, '<C-f>', '<C-f>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-F>', '<C-F>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-n>', '<C-n>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-N>', '<C-N>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-b>', '<C-b>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-P>', '<C-P>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-p>', '<C-p>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-t>', '<C-t>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-T>', '<C-T>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-s>', '<C-s>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-S>', '<C-S>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-r>', '<C-r>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-R>', '<C-R>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-v>', '<C-v>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-V>', '<C-V>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-b>', '<C-b>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-B>', '<C-B>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-d>', '<C-d>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-D>', '<C-D>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-i>', '<C-i>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-I>', '<C-I>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-y>', '<C-y>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-Y>', '<C-Y>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-u>', '<C-u>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-U>', '<C-U>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-e>', '<C-e>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-E>', '<C-E>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-h>', '<C-h>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-H>', '<C-H>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-l>', '<C-l>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-L>', '<C-L>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-k>', '<C-k>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-K>', '<C-K>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-m>', '<C-m>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-M>', '<C-M>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-j>', '<C-j>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-J>', '<C-J>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-;>', '<C-;>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-:>', '<C-:>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-o>', '<C-o>')
        vim.keymap.set({ 'n', 'v', 'i' }, '<C-O>', '<C-O>')
	end
end

vim.keymap.set("n", "<leader><leader>c", function ()
    colmakdhEmulation = not colmakdhEmulation
    setKeyMap()
end)

vim.keymap.set("n", "<leader><leader>q", function ()
    return 
    -- doesn't work yet
    -- qwertyNormalModeEmulation = not qwertyNormalModeEmulation
    -- setKeyMap()
end)

setKeyMap()

